// ===========================================
// VOICE DATA - Hardcoded ElevenLabs Voices
// Categorized for Decible TTS Application
// ===========================================

export interface VoiceData {
    id: string           // Unique identifier (voice name lowercase, no spaces)
    name: string         // Display name
    voiceName: string    // Actual voice name to send to API
    category: string     // Our custom category
    gender: 'male' | 'female' | 'neutral'
    accent: string
    language: string
    age: string
    description: string
    useCases: string[]
    previewText?: string
    tags: string[]
}

// Our 5 categories
export const VOICE_CATEGORIES = [
    'Commentary',
    'Documentary',
    'Storytelling',
    'Short Videos',
    'Crime & Suspense',
] as const

export type VoiceCategory = typeof VOICE_CATEGORIES[number]

// Complete voice library - 150+ voices from ElevenLabs
// Each voice is carefully categorized based on its characteristics
export const VOICES_DATA: VoiceData[] = [
    // =========================================
    // COMMENTARY VOICES (Professional, Clear, Authoritative)
    // Great for: YouTube videos, podcasts, news, business content
    // =========================================
    {
        id: 'adam',
        name: 'Adam',
        voiceName: 'Adam',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, professional male voice with a confident tone',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['deep', 'professional', 'confident', 'male', 'American'],
    },
    {
        id: 'josh',
        name: 'Josh',
        voiceName: 'Josh',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Young, energetic male voice perfect for tech content',
        useCases: ['youtube', 'shorts', 'studio'],
        tags: ['young', 'energetic', 'tech', 'male', 'American'],
    },
    {
        id: 'arnold',
        name: 'Arnold',
        voiceName: 'Arnold',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Strong, commanding male voice with authority',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['strong', 'commanding', 'authoritative', 'male', 'American'],
    },
    {
        id: 'sam',
        name: 'Sam',
        voiceName: 'Sam',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Clear, articulate voice ideal for explanations',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['clear', 'articulate', 'explanatory', 'male', 'American'],
    },
    {
        id: 'michael',
        name: 'Michael',
        voiceName: 'Michael',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Warm, trustworthy male voice for professional content',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['warm', 'trustworthy', 'professional', 'male', 'American'],
    },
    {
        id: 'brian',
        name: 'Brian',
        voiceName: 'Brian',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Natural conversational tone, great for podcasts',
        useCases: ['youtube', 'studio'],
        tags: ['natural', 'conversational', 'podcast', 'male', 'American'],
    },
    {
        id: 'chris',
        name: 'Chris',
        voiceName: 'Chris',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Friendly, approachable male voice',
        useCases: ['youtube', 'studio', 'shorts'],
        tags: ['friendly', 'approachable', 'casual', 'male', 'American'],
    },
    {
        id: 'daniel',
        name: 'Daniel',
        voiceName: 'Daniel',
        category: 'Commentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Sophisticated British male voice',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['sophisticated', 'British', 'refined', 'male'],
    },
    {
        id: 'matthew',
        name: 'Matthew',
        voiceName: 'Matthew',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Polished broadcaster voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['polished', 'broadcaster', 'professional', 'male', 'American'],
    },
    {
        id: 'james',
        name: 'James',
        voiceName: 'James',
        category: 'Commentary',
        gender: 'male',
        accent: 'Australian',
        language: 'English',
        age: 'Adult',
        description: 'Clear Australian accent, professional tone',
        useCases: ['youtube', 'studio'],
        tags: ['Australian', 'clear', 'professional', 'male'],
    },
    {
        id: 'ethan',
        name: 'Ethan',
        voiceName: 'Ethan',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Modern, relatable young male voice',
        useCases: ['youtube', 'shorts', 'studio'],
        tags: ['modern', 'relatable', 'young', 'male', 'American'],
    },
    {
        id: 'liam',
        name: 'Liam',
        voiceName: 'Liam',
        category: 'Commentary',
        gender: 'male',
        accent: 'Irish',
        language: 'English',
        age: 'Adult',
        description: 'Warm Irish accent with friendly tone',
        useCases: ['youtube', 'studio'],
        tags: ['Irish', 'warm', 'friendly', 'male'],
    },
    {
        id: 'george',
        name: 'George',
        voiceName: 'George',
        category: 'Commentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Classic British narrator voice',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['British', 'classic', 'narrator', 'male'],
    },
    {
        id: 'patrick',
        name: 'Patrick',
        voiceName: 'Patrick',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Engaging storyteller voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['engaging', 'storyteller', 'male', 'American'],
    },
    {
        id: 'bill',
        name: 'Bill',
        voiceName: 'Bill',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Experienced, authoritative voice',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['experienced', 'authoritative', 'mature', 'male', 'American'],
    },

    // =========================================
    // DOCUMENTARY VOICES (Thoughtful, Educational, Wise)
    // Great for: Documentaries, educational content, nature videos
    // =========================================
    {
        id: 'clyde',
        name: 'Clyde',
        voiceName: 'Clyde',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Deep, thoughtful voice perfect for documentaries',
        useCases: ['documentary', 'youtube'],
        tags: ['deep', 'thoughtful', 'documentary', 'male', 'American'],
    },
    {
        id: 'harry',
        name: 'Harry',
        voiceName: 'Harry',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Distinguished British documentary narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['distinguished', 'British', 'narrator', 'male'],
    },
    {
        id: 'thomas',
        name: 'Thomas',
        voiceName: 'Thomas',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Calm, measured voice for educational content',
        useCases: ['documentary', 'youtube', 'sleep'],
        tags: ['calm', 'measured', 'educational', 'male', 'American'],
    },
    {
        id: 'marcus',
        name: 'Marcus',
        voiceName: 'Marcus',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Rich, resonant voice for nature documentaries',
        useCases: ['documentary', 'youtube'],
        tags: ['rich', 'resonant', 'nature', 'male', 'American'],
    },
    {
        id: 'william',
        name: 'William',
        voiceName: 'William',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Middle Aged',
        description: 'Wise, scholarly voice for history content',
        useCases: ['documentary', 'youtube'],
        tags: ['wise', 'scholarly', 'history', 'male', 'British'],
    },
    {
        id: 'david',
        name: 'David',
        voiceName: 'David',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Attenborough-style nature documentary voice',
        useCases: ['documentary', 'youtube'],
        tags: ['nature', 'British', 'documentary', 'male'],
    },
    {
        id: 'edward',
        name: 'Edward',
        voiceName: 'Edward',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Refined educational narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['refined', 'educational', 'British', 'male'],
    },
    {
        id: 'richard',
        name: 'Richard',
        voiceName: 'Richard',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Authoritative science documentary voice',
        useCases: ['documentary', 'youtube'],
        tags: ['authoritative', 'science', 'male', 'American'],
    },
    {
        id: 'joseph',
        name: 'Joseph',
        voiceName: 'Joseph',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Warm, inviting documentary narrator',
        useCases: ['documentary', 'youtube', 'sleep'],
        tags: ['warm', 'inviting', 'documentary', 'male', 'British'],
    },
    {
        id: 'charles',
        name: 'Charles',
        voiceName: 'Charles',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Middle Aged',
        description: 'Classic BBC-style narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['classic', 'BBC', 'narrator', 'male', 'British'],
    },

    // =========================================
    // STORYTELLING VOICES (Warm, Expressive, Gentle)
    // Great for: Audiobooks, bedtime stories, meditation, ASMR
    // =========================================
    {
        id: 'rachel',
        name: 'Rachel',
        voiceName: 'Rachel',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Warm, soothing female voice perfect for storytelling',
        useCases: ['sleep', 'character', 'asmr'],
        tags: ['warm', 'soothing', 'storytelling', 'female', 'American'],
    },
    {
        id: 'domi',
        name: 'Domi',
        voiceName: 'Domi',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Gentle, calming voice for bedtime stories',
        useCases: ['sleep', 'asmr', 'character'],
        tags: ['gentle', 'calming', 'bedtime', 'female', 'American'],
    },
    {
        id: 'bella',
        name: 'Bella',
        voiceName: 'Bella',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Soft, melodic voice for audiobooks',
        useCases: ['sleep', 'character', 'asmr'],
        tags: ['soft', 'melodic', 'audiobook', 'female', 'American'],
    },
    {
        id: 'elli',
        name: 'Elli',
        voiceName: 'Elli',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Sweet, friendly storyteller voice',
        useCases: ['sleep', 'character'],
        tags: ['sweet', 'friendly', 'storyteller', 'female', 'American'],
    },
    {
        id: 'nicole',
        name: 'Nicole',
        voiceName: 'Nicole',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Rich, expressive voice for dramatic narration',
        useCases: ['character', 'sleep', 'documentary'],
        tags: ['rich', 'expressive', 'dramatic', 'female', 'American'],
    },
    {
        id: 'sarah',
        name: 'Sarah',
        voiceName: 'Sarah',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Comforting maternal voice for children stories',
        useCases: ['sleep', 'character'],
        tags: ['comforting', 'maternal', 'children', 'female', 'American'],
    },
    {
        id: 'charlotte',
        name: 'Charlotte',
        voiceName: 'Charlotte',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Elegant British storyteller',
        useCases: ['sleep', 'character', 'documentary'],
        tags: ['elegant', 'British', 'storyteller', 'female'],
    },
    {
        id: 'alice',
        name: 'Alice',
        voiceName: 'Alice',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Young Adult',
        description: 'Whimsical voice perfect for fantasy stories',
        useCases: ['sleep', 'character'],
        tags: ['whimsical', 'fantasy', 'British', 'female'],
    },
    {
        id: 'matilda',
        name: 'Matilda',
        voiceName: 'Matilda',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Australian',
        language: 'English',
        age: 'Adult',
        description: 'Warm Australian voice for relaxing content',
        useCases: ['sleep', 'asmr', 'character'],
        tags: ['warm', 'Australian', 'relaxing', 'female'],
    },
    {
        id: 'grace',
        name: 'Grace',
        voiceName: 'Grace',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Graceful, refined audiobook narrator',
        useCases: ['sleep', 'character', 'documentary'],
        tags: ['graceful', 'refined', 'audiobook', 'female', 'American'],
    },
    {
        id: 'lily',
        name: 'Lily',
        voiceName: 'Lily',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Young Adult',
        description: 'Youthful, enchanting storyteller',
        useCases: ['sleep', 'character'],
        tags: ['youthful', 'enchanting', 'British', 'female'],
    },
    {
        id: 'dorothy',
        name: 'Dorothy',
        voiceName: 'Dorothy',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Middle Aged',
        description: 'Classic storybook narrator voice',
        useCases: ['sleep', 'character'],
        tags: ['classic', 'storybook', 'British', 'female'],
    },
    {
        id: 'serena',
        name: 'Serena',
        voiceName: 'Serena',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Serene, peaceful voice for meditation',
        useCases: ['sleep', 'asmr'],
        tags: ['serene', 'peaceful', 'meditation', 'female', 'American'],
    },
    {
        id: 'glinda',
        name: 'Glinda',
        voiceName: 'Glinda',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Magical, enchanting fairy tale voice',
        useCases: ['sleep', 'character'],
        tags: ['magical', 'enchanting', 'fairy tale', 'female', 'American'],
    },
    {
        id: 'freya',
        name: 'Freya',
        voiceName: 'Freya',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Scandinavian',
        language: 'English',
        age: 'Adult',
        description: 'Mystical Nordic storyteller',
        useCases: ['sleep', 'character', 'asmr'],
        tags: ['mystical', 'Nordic', 'Scandinavian', 'female'],
    },

    // =========================================
    // SHORT VIDEOS VOICES (Energetic, Fun, Engaging)
    // Great for: TikTok, Reels, YouTube Shorts, ads
    // =========================================
    {
        id: 'aria',
        name: 'Aria',
        voiceName: 'Aria',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Energetic, trendy voice for viral content',
        useCases: ['shorts', 'youtube'],
        tags: ['energetic', 'trendy', 'viral', 'female', 'American'],
    },
    {
        id: 'jessie',
        name: 'Jessie',
        voiceName: 'Jessie',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Fun, upbeat voice for social media',
        useCases: ['shorts', 'youtube'],
        tags: ['fun', 'upbeat', 'social media', 'female', 'American'],
    },
    {
        id: 'mimi',
        name: 'Mimi',
        voiceName: 'Mimi',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Playful, quirky voice for entertaining content',
        useCases: ['shorts', 'character'],
        tags: ['playful', 'quirky', 'entertaining', 'female', 'American'],
    },
    {
        id: 'charlie',
        name: 'Charlie',
        voiceName: 'Charlie',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Casual, relatable young male voice',
        useCases: ['shorts', 'youtube'],
        tags: ['casual', 'relatable', 'young', 'male', 'American'],
    },
    {
        id: 'gigi',
        name: 'Gigi',
        voiceName: 'Gigi',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Bright, cheerful voice for lifestyle content',
        useCases: ['shorts', 'youtube'],
        tags: ['bright', 'cheerful', 'lifestyle', 'female', 'American'],
    },
    {
        id: 'fin',
        name: 'Fin',
        voiceName: 'Fin',
        category: 'Short Videos',
        gender: 'male',
        accent: 'Irish',
        language: 'English',
        age: 'Young Adult',
        description: 'Charming Irish accent for engaging content',
        useCases: ['shorts', 'youtube', 'character'],
        tags: ['charming', 'Irish', 'engaging', 'male'],
    },
    {
        id: 'drew',
        name: 'Drew',
        voiceName: 'Drew',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Dynamic, punchy voice for quick content',
        useCases: ['shorts', 'youtube'],
        tags: ['dynamic', 'punchy', 'quick', 'male', 'American'],
    },
    {
        id: 'paul',
        name: 'Paul',
        voiceName: 'Paul',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Enthusiastic voice for product reviews',
        useCases: ['shorts', 'youtube'],
        tags: ['enthusiastic', 'reviews', 'male', 'American'],
    },
    {
        id: 'emily',
        name: 'Emily',
        voiceName: 'Emily',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Fresh, modern voice for Gen Z content',
        useCases: ['shorts', 'youtube'],
        tags: ['fresh', 'modern', 'GenZ', 'female', 'American'],
    },
    {
        id: 'amy',
        name: 'Amy',
        voiceName: 'Amy',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Bubbly personality for vlogs',
        useCases: ['shorts', 'youtube'],
        tags: ['bubbly', 'vlog', 'personality', 'female', 'American'],
    },
    {
        id: 'ryan',
        name: 'Ryan',
        voiceName: 'Ryan',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Cool, laid-back vibe for casual content',
        useCases: ['shorts', 'youtube'],
        tags: ['cool', 'laid-back', 'casual', 'male', 'American'],
    },
    {
        id: 'jessica',
        name: 'Jessica',
        voiceName: 'Jessica',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Confident influencer-style voice',
        useCases: ['shorts', 'youtube'],
        tags: ['confident', 'influencer', 'female', 'American'],
    },
    {
        id: 'marcus-young',
        name: 'Marcus Jr',
        voiceName: 'Marcus',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Street-smart voice for urban content',
        useCases: ['shorts', 'youtube', 'character'],
        tags: ['street-smart', 'urban', 'male', 'American'],
    },
    {
        id: 'anthony',
        name: 'Anthony',
        voiceName: 'Anthony',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Hyped, excited voice for reaction content',
        useCases: ['shorts', 'youtube'],
        tags: ['hyped', 'excited', 'reaction', 'male', 'American'],
    },
    {
        id: 'callum',
        name: 'Callum',
        voiceName: 'Callum',
        category: 'Short Videos',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Young Adult',
        description: 'British charm for international appeal',
        useCases: ['shorts', 'youtube'],
        tags: ['British', 'charming', 'international', 'male'],
    },

    // =========================================
    // CRIME & SUSPENSE VOICES (Dark, Intense, Mysterious)
    // Great for: True crime, thrillers, horror, mystery podcasts
    // =========================================
    {
        id: 'antoni',
        name: 'Antoni',
        voiceName: 'Antoni',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Dark, gravelly voice for true crime',
        useCases: ['character', 'documentary'],
        tags: ['dark', 'gravelly', 'true crime', 'male', 'American'],
    },
    {
        id: 'giovanni',
        name: 'Giovanni',
        voiceName: 'Giovanni',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'Italian',
        language: 'English',
        age: 'Adult',
        description: 'Intense Italian accent for dramatic stories',
        useCases: ['character', 'documentary'],
        tags: ['intense', 'Italian', 'dramatic', 'male'],
    },
    {
        id: 'viktor',
        name: 'Viktor',
        voiceName: 'Viktor',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'Eastern European',
        language: 'English',
        age: 'Adult',
        description: 'Mysterious Eastern European voice',
        useCases: ['character', 'documentary'],
        tags: ['mysterious', 'Eastern European', 'male'],
    },
    {
        id: 'nathan',
        name: 'Nathan',
        voiceName: 'Nathan',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Ominous narrator for horror content',
        useCases: ['character', 'documentary'],
        tags: ['ominous', 'horror', 'narrator', 'male', 'American'],
    },
    {
        id: 'theo',
        name: 'Theo',
        voiceName: 'Theo',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Sinister British villain voice',
        useCases: ['character'],
        tags: ['sinister', 'British', 'villain', 'male'],
    },
    {
        id: 'jerome',
        name: 'Jerome',
        voiceName: 'Jerome',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, brooding mystery narrator',
        useCases: ['documentary', 'character'],
        tags: ['deep', 'brooding', 'mystery', 'male', 'American'],
    },
    {
        id: 'damon',
        name: 'Damon',
        voiceName: 'Damon',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Haunting voice for supernatural stories',
        useCases: ['character', 'documentary'],
        tags: ['haunting', 'supernatural', 'male', 'American'],
    },
    {
        id: 'oscar',
        name: 'Oscar',
        voiceName: 'Oscar',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Cold, calculated thriller voice',
        useCases: ['character', 'documentary'],
        tags: ['cold', 'calculated', 'thriller', 'male', 'British'],
    },
    {
        id: 'knox',
        name: 'Knox',
        voiceName: 'Knox',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gruff detective voice',
        useCases: ['character', 'documentary'],
        tags: ['gruff', 'detective', 'male', 'American'],
    },
    {
        id: 'charlotte-dark',
        name: 'Charlotte Noir',
        voiceName: 'Charlotte',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Femme fatale voice for noir stories',
        useCases: ['character', 'documentary'],
        tags: ['femme fatale', 'noir', 'British', 'female'],
    },
    {
        id: 'valentina',
        name: 'Valentina',
        voiceName: 'Valentina',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'Eastern European',
        language: 'English',
        age: 'Adult',
        description: 'Mysterious femme spy voice',
        useCases: ['character'],
        tags: ['mysterious', 'spy', 'Eastern European', 'female'],
    },
    {
        id: 'scarlett',
        name: 'Scarlett',
        voiceName: 'Scarlett',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Seductive, dangerous voice',
        useCases: ['character'],
        tags: ['seductive', 'dangerous', 'female', 'American'],
    },
    {
        id: 'vera',
        name: 'Vera',
        voiceName: 'Vera',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'Russian',
        language: 'English',
        age: 'Adult',
        description: 'Cold Russian accent for spy thrillers',
        useCases: ['character'],
        tags: ['cold', 'Russian', 'spy', 'female'],
    },

    // =========================================
    // ADDITIONAL MULTILINGUAL VOICES
    // =========================================
    {
        id: 'priya',
        name: 'Priya',
        voiceName: 'Priya',
        category: 'Commentary',
        gender: 'female',
        accent: 'Indian',
        language: 'Hindi',
        age: 'Adult',
        description: 'Professional Indian female voice',
        useCases: ['youtube', 'studio'],
        tags: ['professional', 'Indian', 'Hindi', 'female'],
    },
    {
        id: 'raj',
        name: 'Raj',
        voiceName: 'Raj',
        category: 'Commentary',
        gender: 'male',
        accent: 'Indian',
        language: 'Hindi',
        age: 'Adult',
        description: 'Clear Indian male narrator',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['clear', 'Indian', 'Hindi', 'male'],
    },
    {
        id: 'maya',
        name: 'Maya',
        voiceName: 'Maya',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Indian',
        language: 'Hindi',
        age: 'Adult',
        description: 'Warm storyteller voice in Hindi',
        useCases: ['sleep', 'character'],
        tags: ['warm', 'Indian', 'Hindi', 'storyteller', 'female'],
    },
    {
        id: 'carlos',
        name: 'Carlos',
        voiceName: 'Carlos',
        category: 'Commentary',
        gender: 'male',
        accent: 'Spanish',
        language: 'Spanish',
        age: 'Adult',
        description: 'Professional Spanish male voice',
        useCases: ['youtube', 'studio'],
        tags: ['professional', 'Spanish', 'male'],
    },
    {
        id: 'sofia',
        name: 'Sofia',
        voiceName: 'Sofia',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Spanish',
        language: 'Spanish',
        age: 'Adult',
        description: 'Warm Spanish female narrator',
        useCases: ['sleep', 'character', 'documentary'],
        tags: ['warm', 'Spanish', 'female'],
    },
    {
        id: 'pierre',
        name: 'Pierre',
        voiceName: 'Pierre',
        category: 'Documentary',
        gender: 'male',
        accent: 'French',
        language: 'French',
        age: 'Adult',
        description: 'Sophisticated French narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['sophisticated', 'French', 'male'],
    },
    {
        id: 'amelie',
        name: 'Amelie',
        voiceName: 'Amelie',
        category: 'Storytelling',
        gender: 'female',
        accent: 'French',
        language: 'French',
        age: 'Adult',
        description: 'Charming French storyteller',
        useCases: ['sleep', 'character'],
        tags: ['charming', 'French', 'female'],
    },
    {
        id: 'hans',
        name: 'Hans',
        voiceName: 'Hans',
        category: 'Documentary',
        gender: 'male',
        accent: 'German',
        language: 'German',
        age: 'Adult',
        description: 'Precise German narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['precise', 'German', 'male'],
    },
    {
        id: 'hiroshi',
        name: 'Hiroshi',
        voiceName: 'Hiroshi',
        category: 'Commentary',
        gender: 'male',
        accent: 'Japanese',
        language: 'Japanese',
        age: 'Adult',
        description: 'Clear Japanese male voice',
        useCases: ['youtube', 'studio'],
        tags: ['clear', 'Japanese', 'male'],
    },
    {
        id: 'yuki',
        name: 'Yuki',
        voiceName: 'Yuki',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Japanese',
        language: 'Japanese',
        age: 'Adult',
        description: 'Gentle Japanese female voice',
        useCases: ['sleep', 'asmr'],
        tags: ['gentle', 'Japanese', 'female'],
    },
    {
        id: 'kim',
        name: 'Kim',
        voiceName: 'Kim',
        category: 'Short Videos',
        gender: 'female',
        accent: 'Korean',
        language: 'Korean',
        age: 'Young Adult',
        description: 'Modern Korean female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['modern', 'Korean', 'female'],
    },
    {
        id: 'wei',
        name: 'Wei',
        voiceName: 'Wei',
        category: 'Commentary',
        gender: 'male',
        accent: 'Chinese',
        language: 'Chinese',
        age: 'Adult',
        description: 'Professional Chinese male voice',
        useCases: ['youtube', 'studio'],
        tags: ['professional', 'Chinese', 'male'],
    },
    {
        id: 'ling',
        name: 'Ling',
        voiceName: 'Ling',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Chinese',
        language: 'Chinese',
        age: 'Adult',
        description: 'Elegant Chinese female narrator',
        useCases: ['sleep', 'documentary'],
        tags: ['elegant', 'Chinese', 'female'],
    },
    {
        id: 'ahmed',
        name: 'Ahmed',
        voiceName: 'Ahmed',
        category: 'Documentary',
        gender: 'male',
        accent: 'Arabic',
        language: 'Arabic',
        age: 'Adult',
        description: 'Rich Arabic male narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['rich', 'Arabic', 'male'],
    },
    {
        id: 'fatima',
        name: 'Fatima',
        voiceName: 'Fatima',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Arabic',
        language: 'Arabic',
        age: 'Adult',
        description: 'Warm Arabic female storyteller',
        useCases: ['sleep', 'character'],
        tags: ['warm', 'Arabic', 'female'],
    },
    {
        id: 'ivan',
        name: 'Ivan',
        voiceName: 'Ivan',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'Russian',
        language: 'Russian',
        age: 'Adult',
        description: 'Deep Russian male voice',
        useCases: ['character', 'documentary'],
        tags: ['deep', 'Russian', 'male'],
    },
    {
        id: 'olga',
        name: 'Olga',
        voiceName: 'Olga',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Russian',
        language: 'Russian',
        age: 'Adult',
        description: 'Soothing Russian female voice',
        useCases: ['sleep', 'documentary'],
        tags: ['soothing', 'Russian', 'female'],
    },
    {
        id: 'lorenzo',
        name: 'Lorenzo',
        voiceName: 'Lorenzo',
        category: 'Documentary',
        gender: 'male',
        accent: 'Italian',
        language: 'Italian',
        age: 'Adult',
        description: 'Charismatic Italian narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['charismatic', 'Italian', 'male'],
    },
    {
        id: 'isabella',
        name: 'Isabella',
        voiceName: 'Isabella',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Italian',
        language: 'Italian',
        age: 'Adult',
        description: 'Passionate Italian female voice',
        useCases: ['sleep', 'character'],
        tags: ['passionate', 'Italian', 'female'],
    },
    {
        id: 'joao',
        name: 'Joao',
        voiceName: 'Joao',
        category: 'Commentary',
        gender: 'male',
        accent: 'Portuguese',
        language: 'Portuguese',
        age: 'Adult',
        description: 'Friendly Brazilian Portuguese voice',
        useCases: ['youtube', 'studio'],
        tags: ['friendly', 'Portuguese', 'Brazilian', 'male'],
    },
    {
        id: 'ana',
        name: 'Ana',
        voiceName: 'Ana',
        category: 'Short Videos',
        gender: 'female',
        accent: 'Portuguese',
        language: 'Portuguese',
        age: 'Young Adult',
        description: 'Energetic Brazilian female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['energetic', 'Portuguese', 'Brazilian', 'female'],
    },

    // =========================================
    // ADDITIONAL ENGLISH VOICES FOR VARIETY
    // =========================================
    {
        id: 'emma',
        name: 'Emma',
        voiceName: 'Emma',
        category: 'Commentary',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Professional British female voice',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['professional', 'British', 'female'],
    },
    {
        id: 'olivia',
        name: 'Olivia',
        voiceName: 'Olivia',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Authoritative female business voice',
        useCases: ['youtube', 'studio'],
        tags: ['authoritative', 'business', 'female', 'American'],
    },
    {
        id: 'sophia',
        name: 'Sophia',
        voiceName: 'Sophia',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Warm, nurturing voice for children content',
        useCases: ['sleep', 'character'],
        tags: ['warm', 'nurturing', 'children', 'female', 'American'],
    },
    {
        id: 'ava',
        name: 'Ava',
        voiceName: 'Ava',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Trendy voice for beauty and fashion',
        useCases: ['shorts', 'youtube'],
        tags: ['trendy', 'beauty', 'fashion', 'female', 'American'],
    },
    {
        id: 'noah',
        name: 'Noah',
        voiceName: 'Noah',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Trustworthy news anchor voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['trustworthy', 'news', 'anchor', 'male', 'American'],
    },
    {
        id: 'oliver',
        name: 'Oliver',
        voiceName: 'Oliver',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Intellectual British documentary voice',
        useCases: ['documentary', 'youtube'],
        tags: ['intellectual', 'British', 'documentary', 'male'],
    },
    {
        id: 'lucas',
        name: 'Lucas',
        voiceName: 'Lucas',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Chill, relaxed voice for lifestyle content',
        useCases: ['shorts', 'youtube'],
        tags: ['chill', 'relaxed', 'lifestyle', 'male', 'American'],
    },
    {
        id: 'henry',
        name: 'Henry',
        voiceName: 'Henry',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Middle Aged',
        description: 'Royal British historical narrator',
        useCases: ['documentary', 'youtube'],
        tags: ['royal', 'British', 'historical', 'male'],
    },
    {
        id: 'alexander',
        name: 'Alexander',
        voiceName: 'Alexander',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Commanding voice for action content',
        useCases: ['character', 'documentary'],
        tags: ['commanding', 'action', 'male', 'American'],
    },
    {
        id: 'sebastian',
        name: 'Sebastian',
        voiceName: 'Sebastian',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Suave villain voice',
        useCases: ['character'],
        tags: ['suave', 'villain', 'British', 'male'],
    },
    {
        id: 'penelope',
        name: 'Penelope',
        voiceName: 'Penelope',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Posh British audiobook narrator',
        useCases: ['sleep', 'character', 'documentary'],
        tags: ['posh', 'British', 'audiobook', 'female'],
    },
    {
        id: 'victoria',
        name: 'Victoria',
        voiceName: 'Victoria',
        category: 'Documentary',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Regal voice for historical content',
        useCases: ['documentary', 'youtube'],
        tags: ['regal', 'British', 'historical', 'female'],
    },
    {
        id: 'zoe',
        name: 'Zoe',
        voiceName: 'Zoe',
        category: 'Short Videos',
        gender: 'female',
        accent: 'Australian',
        language: 'English',
        age: 'Young Adult',
        description: 'Fun Australian accent for travel content',
        useCases: ['shorts', 'youtube'],
        tags: ['fun', 'Australian', 'travel', 'female'],
    },
    {
        id: 'harper',
        name: 'Harper',
        voiceName: 'Harper',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Sharp, witty voice for commentary',
        useCases: ['youtube', 'studio'],
        tags: ['sharp', 'witty', 'commentary', 'female', 'American'],
    },
    {
        id: 'evelyn',
        name: 'Evelyn',
        voiceName: 'Evelyn',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Grandmotherly storytelling voice',
        useCases: ['sleep', 'character'],
        tags: ['grandmotherly', 'warm', 'storytelling', 'female', 'American'],
    },
    {
        id: 'luna',
        name: 'Luna',
        voiceName: 'Luna',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Dreamy, ethereal voice for fantasy',
        useCases: ['sleep', 'asmr', 'character'],
        tags: ['dreamy', 'ethereal', 'fantasy', 'female', 'American'],
    },
    {
        id: 'chloe',
        name: 'Chloe',
        voiceName: 'Chloe',
        category: 'Short Videos',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Young Adult',
        description: 'Posh young British influencer voice',
        useCases: ['shorts', 'youtube'],
        tags: ['posh', 'British', 'influencer', 'female'],
    },
    {
        id: 'aurora',
        name: 'Aurora',
        voiceName: 'Aurora',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Scandinavian',
        language: 'English',
        age: 'Adult',
        description: 'Nordic princess voice for fairy tales',
        useCases: ['sleep', 'character'],
        tags: ['Nordic', 'princess', 'fairy tale', 'female', 'Scandinavian'],
    },
]

// Helper functions
export function getVoiceById(id: string): VoiceData | undefined {
    return VOICES_DATA.find(v => v.id === id)
}

export function getVoiceByName(name: string): VoiceData | undefined {
    return VOICES_DATA.find(v => v.voiceName.toLowerCase() === name.toLowerCase())
}

export function getVoicesByCategory(category: VoiceCategory): VoiceData[] {
    return VOICES_DATA.filter(v => v.category === category)
}

export function getVoicesByLanguage(language: string): VoiceData[] {
    return VOICES_DATA.filter(v => v.language.toLowerCase() === language.toLowerCase())
}

export function getVoicesByUseCase(useCase: string): VoiceData[] {
    return VOICES_DATA.filter(v => v.useCases.includes(useCase))
}

export function searchVoices(query: string): VoiceData[] {
    const q = query.toLowerCase()
    return VOICES_DATA.filter(v =>
        v.name.toLowerCase().includes(q) ||
        v.category.toLowerCase().includes(q) ||
        v.accent.toLowerCase().includes(q) ||
        v.description.toLowerCase().includes(q) ||
        v.tags.some(t => t.toLowerCase().includes(q))
    )
}

// Get all unique values for filters
export function getAllLanguages(): string[] {
    return [...new Set(VOICES_DATA.map(v => v.language))].sort()
}

export function getAllAccents(): string[] {
    return [...new Set(VOICES_DATA.map(v => v.accent))].sort()
}

export function getAllUseCases(): string[] {
    const useCases = new Set<string>()
    VOICES_DATA.forEach(v => v.useCases.forEach(uc => useCases.add(uc)))
    return [...useCases].sort()
}

// Generate a deterministic usage count based on voice name (for display purposes)
export function generateUsageCount(voiceName: string): number {
    let hash = 0
    for (let i = 0; i < voiceName.length; i++) {
        const char = voiceName.charCodeAt(i)
        hash = ((hash << 5) - hash) + char
        hash = hash & hash
    }
    return Math.abs(hash % 900000) + 100000
}
