// ===========================================
// VOICE DATA - Kie.ai ElevenLabs v2.5 Turbo
// Supports preset names AND ElevenLabs voice IDs
// Static previews via: https://static.aiquickdraw.com/elevenlabs/voice/<id>.mp3
// ===========================================

export interface VoiceData {
    id: string           // Unique identifier (voice name lowercase, no spaces)
    name: string         // Display name shown to user
    voiceName: string    // Value sent to Kie.ai API (preset name OR ElevenLabs voice ID)
    elevenLabsId?: string // ElevenLabs voice ID for preview URLs and extended voices
    category: string     // Our custom category
    gender: 'male' | 'female' | 'neutral'
    accent: string
    language: string
    age: string
    description: string
    useCases: string[]
    previewText?: string
    tags: string[]
}

// Our 9 categories
export const VOICE_CATEGORIES = [
    'Commentary',
    'Documentary',
    'Storytelling',
    'Short Videos',
    'Crime & Suspense',
    'Character',
    'Meditation & ASMR',
    'Announcer & Radio',
    'Conversational',
] as const

export type VoiceCategory = typeof VOICE_CATEGORIES[number]

// Static preview URL base (from Kie.ai docs)
export const VOICE_PREVIEW_BASE_URL = 'https://static.aiquickdraw.com/elevenlabs/voice'

// Kie.ai supported preset voice names (can be used directly by name)
export const SUPPORTED_PRESET_NAMES = [
    'Rachel', 'Aria', 'Roger', 'Sarah', 'Laura',
    'Charlie', 'George', 'Callum', 'River', 'Liam',
    'Charlotte', 'Alice', 'Matilda', 'Will', 'Jessica',
    'Eric', 'Chris', 'Brian', 'Daniel', 'Lily', 'Bill',
] as const

// Complete voice library — 130+ voices
// - Preset voices: voiceName = human-readable name (e.g. "Rachel")
// - Extended voices: voiceName = ElevenLabs voice ID (e.g. "BIvP0GN1cAtSRTxNHnWS")
// Both are accepted by Kie.ai API input.voice field
export const VOICES_DATA: VoiceData[] = [
    // =========================================
    // COMMENTARY VOICES (Professional, Clear, Authoritative)
    // Great for: YouTube videos, podcasts, news, business content
    // =========================================
    {
        id: 'brian',
        name: 'Brian',
        voiceName: 'Brian',
        elevenLabsId: 'nPczCjzI2devNBz1zQrb',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Natural conversational tone, great for podcasts and YouTube',
        useCases: ['youtube', 'studio'],
        tags: ['natural', 'conversational', 'podcast', 'male', 'American'],
    },
    {
        id: 'chris',
        name: 'Chris',
        voiceName: 'Chris',
        elevenLabsId: 'iP95p4xoKVk53GoZ742B',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Friendly, approachable male voice for commentary',
        useCases: ['youtube', 'studio', 'shorts'],
        tags: ['friendly', 'approachable', 'casual', 'male', 'American'],
    },
    {
        id: 'bill',
        name: 'Bill',
        voiceName: 'Bill',
        elevenLabsId: 'pqHfZKP75CvOlQylNhV4',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Experienced, authoritative voice for commentary',
        useCases: ['youtube', 'documentary', 'studio'],
        tags: ['experienced', 'authoritative', 'mature', 'male', 'American'],
    },
    {
        id: 'roger',
        name: 'Roger',
        voiceName: 'Roger',
        elevenLabsId: 'CwhRBWXzGAHq8TQ4Fs17',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Deep, confident male voice with a broadcast quality',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['deep', 'confident', 'broadcast', 'male', 'American'],
    },
    {
        id: 'ellen',
        name: 'Ellen',
        voiceName: 'BIvP0GN1cAtSRTxNHnWS',
        elevenLabsId: 'BIvP0GN1cAtSRTxNHnWS',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Serious, direct and confident female voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['serious', 'direct', 'confident', 'female', 'American'],
    },
    {
        id: 'juniper',
        name: 'Juniper',
        voiceName: 'aMSt68OGf4xUZAnLpTU8',
        elevenLabsId: 'aMSt68OGf4xUZAnLpTU8',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Grounded and professional female voice',
        useCases: ['youtube', 'studio'],
        tags: ['grounded', 'professional', 'female', 'American'],
    },
    {
        id: 'bradford',
        name: 'Bradford',
        voiceName: 'NNl6r8mD7vthiJatiJt1',
        elevenLabsId: 'NNl6r8mD7vthiJatiJt1',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Expressive and articulate male voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['expressive', 'articulate', 'male', 'American'],
    },
    {
        id: 'cassidy',
        name: 'Cassidy',
        voiceName: '56AoDkrOh6qfVPDXZ7Pt',
        elevenLabsId: '56AoDkrOh6qfVPDXZ7Pt',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Crisp, direct and clear female voice',
        useCases: ['youtube', 'studio'],
        tags: ['crisp', 'direct', 'clear', 'female', 'American'],
    },
    {
        id: 'bella',
        name: 'Bella',
        voiceName: 'hpp4J3VqNfWAUOO0d1Us',
        elevenLabsId: 'hpp4J3VqNfWAUOO0d1Us',
        category: 'Commentary',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Professional, bright and warm female voice',
        useCases: ['youtube', 'studio'],
        tags: ['professional', 'bright', 'warm', 'female', 'American'],
    },
    {
        id: 'jeff',
        name: 'Jeff',
        voiceName: 'gs0tAILXbY5DNrJrsM6F',
        elevenLabsId: 'gs0tAILXbY5DNrJrsM6F',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Classy, resonating and strong male voice',
        useCases: ['youtube', 'studio', 'documentary'],
        tags: ['classy', 'resonating', 'strong', 'male', 'American'],
    },
    {
        id: 'tom-conversations',
        name: 'Tom',
        voiceName: 'DYkrAHD8iwork3YSUBbs',
        elevenLabsId: 'DYkrAHD8iwork3YSUBbs',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Conversations and books, natural male voice',
        useCases: ['youtube', 'studio'],
        tags: ['natural', 'conversational', 'books', 'male', 'American'],
    },
    {
        id: 'paul-french',
        name: 'Paul French',
        voiceName: 'cTNP6ZM2mLTKj2BFhxEh',
        elevenLabsId: 'cTNP6ZM2mLTKj2BFhxEh',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Podcaster voice, polished and articulate',
        useCases: ['youtube', 'studio'],
        tags: ['podcaster', 'polished', 'articulate', 'male', 'American'],
    },
    {
        id: 'matthew-casual',
        name: 'Matthew',
        voiceName: 'IjnA9kwZJHJ20Fp7Vmy6',
        elevenLabsId: 'IjnA9kwZJHJ20Fp7Vmy6',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Casual, friendly and smooth male voice',
        useCases: ['youtube', 'studio', 'shorts'],
        tags: ['casual', 'friendly', 'smooth', 'male', 'American'],
    },
    {
        id: 'mark-casual',
        name: 'Mark',
        voiceName: '1SM7GgM6IMuvQlz2BwM3',
        elevenLabsId: '1SM7GgM6IMuvQlz2BwM3',
        category: 'Commentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Casual, relaxed and light male voice',
        useCases: ['youtube', 'studio'],
        tags: ['casual', 'relaxed', 'light', 'male', 'American'],
    },
    {
        id: 'addison',
        name: 'Addison 2.0',
        voiceName: 'eR40ATw9ArzDf9h3v7t7',
        elevenLabsId: 'eR40ATw9ArzDf9h3v7t7',
        category: 'Commentary',
        gender: 'female',
        accent: 'Australian',
        language: 'English',
        age: 'Adult',
        description: 'Australian audiobook and podcast voice',
        useCases: ['youtube', 'studio'],
        tags: ['Australian', 'audiobook', 'podcast', 'female'],
    },

    // =========================================
    // DOCUMENTARY VOICES (Thoughtful, Educational, Wise)
    // Great for: Documentaries, educational content, nature videos
    // =========================================
    {
        id: 'george',
        name: 'George',
        voiceName: 'George',
        elevenLabsId: 'JBFqnCBsd6RMkjVDRZzb',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Classic British narrator, perfect for documentaries',
        useCases: ['documentary', 'youtube'],
        tags: ['British', 'classic', 'narrator', 'male'],
    },
    {
        id: 'liam',
        name: 'Liam',
        voiceName: 'Liam',
        elevenLabsId: 'TX3LPaxmHKxFdv7VOQHJ',
        category: 'Documentary',
        gender: 'male',
        accent: 'Irish',
        language: 'English',
        age: 'Adult',
        description: 'Warm Irish accent, thoughtful and engaging',
        useCases: ['documentary', 'youtube', 'studio'],
        tags: ['Irish', 'warm', 'thoughtful', 'male'],
    },
    {
        id: 'will',
        name: 'Will',
        voiceName: 'Will',
        elevenLabsId: 'bIHbv24MWmeRgasZH58o',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Calm, measured voice for educational and documentary content',
        useCases: ['documentary', 'youtube', 'sleep'],
        tags: ['calm', 'measured', 'educational', 'male', 'American'],
    },
    {
        id: 'eric',
        name: 'Eric',
        voiceName: 'Eric',
        elevenLabsId: 'cjVigY5qzO86Huf0OWal',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Rich, resonant voice for nature and history documentaries',
        useCases: ['documentary', 'youtube'],
        tags: ['rich', 'resonant', 'nature', 'male', 'American'],
    },
    {
        id: 'daniel',
        name: 'Daniel',
        voiceName: 'Daniel',
        elevenLabsId: 'onwK4e9ZLuTAKqWW03F9',
        category: 'Documentary',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Sophisticated British male voice for professional documentaries',
        useCases: ['documentary', 'youtube', 'studio'],
        tags: ['sophisticated', 'British', 'refined', 'male'],
    },
    {
        id: 'celian',
        name: 'Celian',
        voiceName: 'DGTOOUoGpoP6UZ9uSWfA',
        elevenLabsId: 'DGTOOUoGpoP6UZ9uSWfA',
        category: 'Documentary',
        gender: 'male',
        accent: 'French',
        language: 'English',
        age: 'Adult',
        description: 'Documentary narrator with a French-accented sophistication',
        useCases: ['documentary', 'youtube'],
        tags: ['French', 'documentary', 'narrator', 'male'],
    },
    {
        id: 'pro-narrator',
        name: 'Pro Narrator',
        voiceName: 'KoQQbl9zjAdLgKZjm8Ol',
        elevenLabsId: 'KoQQbl9zjAdLgKZjm8Ol',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Convincing storyteller with a professional narrator quality',
        useCases: ['documentary', 'youtube', 'studio'],
        tags: ['professional', 'storyteller', 'convincing', 'male', 'American'],
    },
    {
        id: 'hank',
        name: 'Hank',
        voiceName: '6F5Zhi321D3Oq7v1oNT4',
        elevenLabsId: '6F5Zhi321D3Oq7v1oNT4',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep and engaging narrator voice',
        useCases: ['documentary', 'youtube'],
        tags: ['deep', 'engaging', 'narrator', 'male', 'American'],
    },
    {
        id: 'johnny-kid',
        name: 'Johnny Kid',
        voiceName: '8JVbfL6oEdmuxKn5DK2C',
        elevenLabsId: '8JVbfL6oEdmuxKn5DK2C',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Serious and calm narrator voice',
        useCases: ['documentary', 'youtube'],
        tags: ['serious', 'calm', 'narrator', 'male', 'American'],
    },
    {
        id: 'james',
        name: 'James',
        voiceName: 'EkK5I93UQWFDigLMpZcX',
        elevenLabsId: 'EkK5I93UQWFDigLMpZcX',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Husky, engaging and bold male voice',
        useCases: ['documentary', 'youtube', 'studio'],
        tags: ['husky', 'engaging', 'bold', 'male', 'American'],
    },
    {
        id: 'burt-reynolds',
        name: 'Burt Reynolds',
        voiceName: '4YYIPFl9wE5c4L2eu2Gb',
        elevenLabsId: '4YYIPFl9wE5c4L2eu2Gb',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, smooth and clear male voice',
        useCases: ['documentary', 'youtube'],
        tags: ['deep', 'smooth', 'clear', 'male', 'American'],
    },
    {
        id: 'john-doe',
        name: 'John Doe',
        voiceName: 'EiNlNiXeDU1pqqOPrYMO',
        elevenLabsId: 'EiNlNiXeDU1pqqOPrYMO',
        category: 'Documentary',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep male voice for narration',
        useCases: ['documentary', 'youtube'],
        tags: ['deep', 'narration', 'male', 'American'],
    },
    {
        id: 'viraj',
        name: 'Viraj',
        voiceName: 'P1bg08DkjqiVEzOn76yG',
        elevenLabsId: 'P1bg08DkjqiVEzOn76yG',
        category: 'Documentary',
        gender: 'male',
        accent: 'Indian',
        language: 'English',
        age: 'Adult',
        description: 'Rich and soft male voice',
        useCases: ['documentary', 'youtube'],
        tags: ['rich', 'soft', 'Indian', 'male'],
    },

    // =========================================
    // STORYTELLING VOICES (Expressive, Warm, Immersive)
    // Great for: Audiobooks, children stories, bedtime stories
    // =========================================
    {
        id: 'rachel',
        name: 'Rachel',
        voiceName: 'Rachel',
        elevenLabsId: '21m00Tcm4TlvDq8ikWAM',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Warm, expressive female voice for storytelling',
        useCases: ['youtube', 'sleep', 'character'],
        tags: ['warm', 'expressive', 'storytelling', 'female', 'American'],
    },
    {
        id: 'alice',
        name: 'Alice',
        voiceName: 'Alice',
        elevenLabsId: 'Xb7hH8MSUJpSbSDYk0k2',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Gentle, whimsical voice for fairy tales and stories',
        useCases: ['sleep', 'character', 'youtube'],
        tags: ['gentle', 'whimsical', 'fairy tale', 'female', 'British'],
    },
    {
        id: 'matilda',
        name: 'Matilda',
        voiceName: 'Matilda',
        elevenLabsId: 'XrExE9yKIg1WjnnlVkGX',
        category: 'Storytelling',
        gender: 'female',
        accent: 'Australian',
        language: 'English',
        age: 'Adult',
        description: 'Warm Australian accent, natural and engaging storyteller',
        useCases: ['youtube', 'sleep', 'character'],
        tags: ['warm', 'Australian', 'natural', 'female'],
    },
    {
        id: 'callum',
        name: 'Callum',
        voiceName: 'Callum',
        elevenLabsId: 'N2lVS1w4EtoT3dr4eOWO',
        category: 'Storytelling',
        gender: 'male',
        accent: 'Scottish',
        language: 'English',
        age: 'Adult',
        description: 'Scottish accent, captivating voice for adventure stories',
        useCases: ['character', 'youtube', 'documentary'],
        tags: ['Scottish', 'captivating', 'adventure', 'male'],
    },
    {
        id: 'lily',
        name: 'Lily',
        voiceName: 'Lily',
        elevenLabsId: 'pFZP5JQG7iQjIQuC4Bku',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Young Adult',
        description: 'Sweet, melodic voice for bedtime and children stories',
        useCases: ['sleep', 'character', 'asmr'],
        tags: ['sweet', 'melodic', 'bedtime', 'female', 'British'],
    },
    {
        id: 'arabella',
        name: 'Arabella',
        voiceName: 'Z3R5wn05IrDiVCyEkUrK',
        elevenLabsId: 'Z3R5wn05IrDiVCyEkUrK',
        category: 'Storytelling',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Mysterious and emotive female voice',
        useCases: ['sleep', 'character', 'youtube'],
        tags: ['mysterious', 'emotive', 'female', 'British'],
    },
    {
        id: 'olivia',
        name: 'Olivia',
        voiceName: '1hlpeD1ydbI2ow0Tt3EW',
        elevenLabsId: '1hlpeD1ydbI2ow0Tt3EW',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Smooth, warm and engaging female voice',
        useCases: ['sleep', 'youtube', 'character'],
        tags: ['smooth', 'warm', 'engaging', 'female', 'American'],
    },
    {
        id: 'ana-rita',
        name: 'Ana Rita',
        voiceName: 'wJqPPQ618aTW29mptyoc',
        elevenLabsId: 'wJqPPQ618aTW29mptyoc',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Smooth, expressive and bright female voice',
        useCases: ['sleep', 'youtube', 'character'],
        tags: ['smooth', 'expressive', 'bright', 'female', 'American'],
    },
    {
        id: 'myrrdin',
        name: 'Myrrdin',
        voiceName: 'oR4uRy4fHDUGGISL0Rev',
        elevenLabsId: 'oR4uRy4fHDUGGISL0Rev',
        category: 'Storytelling',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Middle Aged',
        description: 'Wise and magical narrator voice',
        useCases: ['sleep', 'character', 'youtube'],
        tags: ['wise', 'magical', 'narrator', 'male', 'British'],
    },
    {
        id: 'jane',
        name: 'Jane',
        voiceName: 'RILOU7YmBhvwJGDGjNmP',
        elevenLabsId: 'RILOU7YmBhvwJGDGjNmP',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Professional audiobook reader',
        useCases: ['sleep', 'youtube', 'studio'],
        tags: ['professional', 'audiobook', 'reader', 'female', 'American'],
    },
    {
        id: 'felix',
        name: 'Felix',
        voiceName: 'Sq93GQT4X1lKDXsQcixO',
        elevenLabsId: 'Sq93GQT4X1lKDXsQcixO',
        category: 'Storytelling',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Warm, positive, contemporary RP male voice',
        useCases: ['youtube', 'sleep', 'character'],
        tags: ['warm', 'positive', 'contemporary', 'British', 'male'],
    },
    {
        id: 'hope-poetic',
        name: 'Hope (Poetic)',
        voiceName: 'iCrDUkL56s3C8sCRl7wb',
        elevenLabsId: 'iCrDUkL56s3C8sCRl7wb',
        category: 'Storytelling',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Poetic, romantic and captivating female voice',
        useCases: ['sleep', 'character', 'youtube'],
        tags: ['poetic', 'romantic', 'captivating', 'female', 'American'],
    },

    // =========================================
    // SHORT VIDEOS VOICES (Energetic, Trendy, Casual)
    // Great for: TikTok, YouTube Shorts, Reels, memes
    // =========================================
    {
        id: 'aria',
        name: 'Aria',
        voiceName: 'Aria',
        elevenLabsId: '9BWtsMINqrJLrRacOk9x',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Trendy, energetic voice perfect for reels and shorts',
        useCases: ['shorts', 'youtube', 'character'],
        tags: ['trendy', 'energetic', 'reels', 'female', 'American'],
    },
    {
        id: 'charlie',
        name: 'Charlie',
        voiceName: 'Charlie',
        elevenLabsId: 'IKne3meq5aSn9XLyUdCD',
        category: 'Short Videos',
        gender: 'male',
        accent: 'Australian',
        language: 'English',
        age: 'Young Adult',
        description: 'Laid-back Australian voice, great for casual short-form content',
        useCases: ['shorts', 'youtube'],
        tags: ['laid-back', 'Australian', 'casual', 'male'],
    },
    {
        id: 'jessica',
        name: 'Jessica',
        voiceName: 'Jessica',
        elevenLabsId: 'cgSgspJ2msm6clMCkdW9',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Bright, relatable female voice for TikTok and YouTube Shorts',
        useCases: ['shorts', 'youtube', 'studio'],
        tags: ['bright', 'relatable', 'social media', 'female', 'American'],
    },
    {
        id: 'river',
        name: 'River',
        voiceName: 'River',
        elevenLabsId: 'SAz9YHcvj6GT2YYXdXww',
        category: 'Short Videos',
        gender: 'neutral',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Gender-neutral, modern voice for inclusive content',
        useCases: ['shorts', 'youtube', 'character'],
        tags: ['neutral', 'modern', 'inclusive', 'American'],
    },
    {
        id: 'brittney',
        name: 'Brittney',
        voiceName: 'kPzsL2i3teMYv0FxEYQ6',
        elevenLabsId: 'kPzsL2i3teMYv0FxEYQ6',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Social media voice, trendy and relatable',
        useCases: ['shorts', 'youtube'],
        tags: ['social media', 'trendy', 'relatable', 'female', 'American'],
    },
    {
        id: 'eve',
        name: 'Eve',
        voiceName: 'BZgkqPqms7Kj9ulSkVzn',
        elevenLabsId: 'BZgkqPqms7Kj9ulSkVzn',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Authentic, energetic and happy female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['authentic', 'energetic', 'happy', 'female', 'American'],
    },
    {
        id: 'heather-rey',
        name: 'Heather Rey',
        voiceName: 'MnUw1cSnpiLoLhpd3Hqp',
        elevenLabsId: 'MnUw1cSnpiLoLhpd3Hqp',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Rushed and friendly female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['rushed', 'friendly', 'female', 'American'],
    },
    {
        id: 'lucy',
        name: 'Lucy',
        voiceName: 'lcMyyd2HUfFzxdCaC4Ta',
        elevenLabsId: 'lcMyyd2HUfFzxdCaC4Ta',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Fresh and casual female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['fresh', 'casual', 'female', 'American'],
    },
    {
        id: 'emma',
        name: 'Emma',
        voiceName: 'pPdl9cQBQq4p6mRkZy2Z',
        elevenLabsId: 'pPdl9cQBQq4p6mRkZy2Z',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Adorable and upbeat female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['adorable', 'upbeat', 'female', 'American'],
    },
    {
        id: 'amelia',
        name: 'Amelia',
        voiceName: 'ZF6FPAbjXT4488VcRRnw',
        elevenLabsId: 'ZF6FPAbjXT4488VcRRnw',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Enthusiastic and expressive female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['enthusiastic', 'expressive', 'female', 'American'],
    },
    {
        id: 'jamahal',
        name: 'Jamahal',
        voiceName: 'DTKMou8ccj1ZaWGBiotd',
        elevenLabsId: 'DTKMou8ccj1ZaWGBiotd',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Young, vibrant and natural male voice',
        useCases: ['shorts', 'youtube'],
        tags: ['young', 'vibrant', 'natural', 'male', 'American'],
    },
    {
        id: 'finn',
        name: 'Finn',
        voiceName: 'vBKc2FfBKJfcZNyEt1n6',
        elevenLabsId: 'vBKc2FfBKJfcZNyEt1n6',
        category: 'Short Videos',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Youthful, eager and energetic male voice',
        useCases: ['shorts', 'youtube'],
        tags: ['youthful', 'eager', 'energetic', 'male', 'American'],
    },
    {
        id: 'tiffany',
        name: 'Tiffany',
        voiceName: '6aDn1KB0hjpdcocrUkmq',
        elevenLabsId: '6aDn1KB0hjpdcocrUkmq',
        category: 'Short Videos',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Natural and welcoming female voice',
        useCases: ['shorts', 'youtube'],
        tags: ['natural', 'welcoming', 'female', 'American'],
    },

    // =========================================
    // CRIME & SUSPENSE VOICES (Dark, Intense, Dramatic)
    // Great for: True crime, horror, thriller, mystery content
    // =========================================
    {
        id: 'sarah',
        name: 'Sarah',
        voiceName: 'Sarah',
        elevenLabsId: 'EXAVITQu4vr4xnSDxMaL',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Compelling, intense voice for true crime narration',
        useCases: ['youtube', 'documentary'],
        tags: ['compelling', 'intense', 'true crime', 'female', 'American'],
    },
    {
        id: 'charlotte',
        name: 'Charlotte',
        voiceName: 'Charlotte',
        elevenLabsId: 'XB0fDUnXU5powFXDhCwa',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Mysterious British voice, perfect for suspense and thriller narration',
        useCases: ['youtube', 'documentary', 'character'],
        tags: ['mysterious', 'British', 'suspense', 'female'],
    },
    {
        id: 'laura',
        name: 'Laura',
        voiceName: 'Laura',
        elevenLabsId: 'FGY2WhTYpPnrIDTdsKH5',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Serious, dramatic voice for crime documentaries',
        useCases: ['youtube', 'documentary'],
        tags: ['serious', 'dramatic', 'crime', 'female', 'American'],
    },
    {
        id: 'parasyte',
        name: 'Parasyte',
        voiceName: '1KFdM0QCwQn4rmn5nn9C',
        elevenLabsId: '1KFdM0QCwQn4rmn5nn9C',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Whispers from the deep dark, eerie and haunting',
        useCases: ['youtube', 'character'],
        tags: ['whisper', 'dark', 'eerie', 'haunting', 'male', 'American'],
    },
    {
        id: 'aria-sultry-villain',
        name: 'Aria (Sultry Villain)',
        voiceName: 'TC0Zp7WVFzhA8zpTlRqV',
        elevenLabsId: 'TC0Zp7WVFzhA8zpTlRqV',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Sultry villain voice, seductive and dangerous',
        useCases: ['youtube', 'character'],
        tags: ['sultry', 'villain', 'seductive', 'female', 'American'],
    },
    {
        id: 'britney-villain',
        name: 'Britney (Villain)',
        voiceName: 'esy0r39YPLQjOczyOib8',
        elevenLabsId: 'esy0r39YPLQjOczyOib8',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Calm and calculative villain voice',
        useCases: ['youtube', 'character'],
        tags: ['calm', 'calculative', 'villain', 'female', 'American'],
    },
    {
        id: 'matthew-schmitz-tyrant',
        name: 'Matthew Schmitz (Tyrant)',
        voiceName: '0SpgpJ4D3MpHCiWdyTg3',
        elevenLabsId: '0SpgpJ4D3MpHCiWdyTg3',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Elitist tyrant voice, commanding and menacing',
        useCases: ['youtube', 'character'],
        tags: ['elitist', 'tyrant', 'commanding', 'menacing', 'male', 'American'],
    },
    {
        id: 'jean',
        name: 'Jean',
        voiceName: 'eVItLK1UvXctxuaRV2Oq',
        elevenLabsId: 'eVItLK1UvXctxuaRV2Oq',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Alluring and playful femme fatale voice',
        useCases: ['youtube', 'character'],
        tags: ['alluring', 'playful', 'femme fatale', 'female', 'American'],
    },
    {
        id: 'sarcastic-sultry-villain',
        name: 'Sarcastic Sultry Villain',
        voiceName: 'UFO0Yv86wqRxAt1DmXUu',
        elevenLabsId: 'UFO0Yv86wqRxAt1DmXUu',
        category: 'Crime & Suspense',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Sarcastic sultry villain female voice',
        useCases: ['youtube', 'character'],
        tags: ['sarcastic', 'sultry', 'villain', 'female', 'American'],
    },
    {
        id: 'matthew-schmitz-antihero',
        name: 'Matthew Schmitz (Anti-Hero)',
        voiceName: 'bwCXcoVxWNYMlC6Esa8u',
        elevenLabsId: 'bwCXcoVxWNYMlC6Esa8u',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gravel, deep anti-hero voice',
        useCases: ['youtube', 'character'],
        tags: ['gravel', 'deep', 'anti-hero', 'male', 'American'],
    },
    {
        id: 'ian-alien',
        name: 'Ian (Alien)',
        voiceName: 'D2jw4N9m4xePLTQ3IHjU',
        elevenLabsId: 'D2jw4N9m4xePLTQ3IHjU',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Strange and distorted alien voice',
        useCases: ['youtube', 'character'],
        tags: ['strange', 'distorted', 'alien', 'male', 'American'],
    },
    {
        id: 'edward',
        name: 'Edward',
        voiceName: 'zYcjlYFOd3taleS0gkk3',
        elevenLabsId: 'zYcjlYFOd3taleS0gkk3',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Loud, confident and cocky male voice',
        useCases: ['youtube', 'character'],
        tags: ['loud', 'confident', 'cocky', 'male', 'American'],
    },
    {
        id: 'michael-dark',
        name: 'Michael',
        voiceName: 'U1Vk2oyatMdYs096Ety7',
        elevenLabsId: 'U1Vk2oyatMdYs096Ety7',
        category: 'Crime & Suspense',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, dark and urban male voice',
        useCases: ['youtube', 'character'],
        tags: ['deep', 'dark', 'urban', 'male', 'American'],
    },

    // =========================================
    // CHARACTER VOICES (Fantasy, Gaming, Villains, Unique)
    // Great for: Games, animation, fantasy, unique characters
    // =========================================
    {
        id: 'grimblewood',
        name: 'Grimblewood Thornwhisker',
        voiceName: 'ouL9IsyrSnUkCmfnD02u',
        elevenLabsId: 'ouL9IsyrSnUkCmfnD02u',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Snarky gnome character voice',
        useCases: ['character', 'youtube'],
        tags: ['snarky', 'gnome', 'fantasy', 'character', 'male', 'American'],
    },
    {
        id: 'dr-von',
        name: 'Dr. Von',
        voiceName: 'yjJ45q8TVCrtMhEKurxY',
        elevenLabsId: 'yjJ45q8TVCrtMhEKurxY',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Quirky mad scientist character voice',
        useCases: ['character', 'youtube'],
        tags: ['quirky', 'mad scientist', 'character', 'male', 'American'],
    },
    {
        id: 'brock',
        name: 'Brock',
        voiceName: 'DGzg6RaUqxGRTHSBjfgF',
        elevenLabsId: 'DGzg6RaUqxGRTHSBjfgF',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Commanding and loud sergeant voice',
        useCases: ['character', 'youtube'],
        tags: ['commanding', 'loud', 'sergeant', 'military', 'male', 'American'],
    },
    {
        id: 'horatius',
        name: 'Horatius',
        voiceName: 'qXpMhyvQqiRxWQs4qSSB',
        elevenLabsId: 'qXpMhyvQqiRxWQs4qSSB',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Energetic character voice',
        useCases: ['character', 'youtube'],
        tags: ['energetic', 'character', 'male', 'American'],
    },
    {
        id: 'malyx',
        name: 'Malyx',
        voiceName: 'vfaqCOvlrKi4Zp7C2IAm',
        elevenLabsId: 'vfaqCOvlrKi4Zp7C2IAm',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Echoey, menacing and deep demon voice',
        useCases: ['character', 'youtube'],
        tags: ['echoey', 'menacing', 'deep', 'demon', 'male', 'American'],
    },
    {
        id: 'flicker',
        name: 'Flicker',
        voiceName: 'piI8Kku0DcvcL6TTSeQt',
        elevenLabsId: 'piI8Kku0DcvcL6TTSeQt',
        category: 'Character',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Cheerful fairy character voice',
        useCases: ['character', 'youtube'],
        tags: ['cheerful', 'fairy', 'character', 'female', 'American'],
    },
    {
        id: 'viking-bjorn',
        name: 'Viking Bjorn',
        voiceName: 'ljo9gAlSqKOvF6D8sOsX',
        elevenLabsId: 'ljo9gAlSqKOvF6D8sOsX',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Epic medieval raider voice',
        useCases: ['character', 'youtube'],
        tags: ['viking', 'epic', 'medieval', 'raider', 'male', 'American'],
    },
    {
        id: 'pirate-marshal',
        name: 'Pirate Marshal',
        voiceName: 'PPzYpIqttlTYA83688JI',
        elevenLabsId: 'PPzYpIqttlTYA83688JI',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Pirate character voice',
        useCases: ['character', 'youtube'],
        tags: ['pirate', 'character', 'male', 'American'],
    },
    {
        id: 'bob-cowboy',
        name: 'Bob (Cowboy)',
        voiceName: 'KTPVrSVAEUSJRClDzBw7',
        elevenLabsId: 'KTPVrSVAEUSJRClDzBw7',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Rugged and warm cowboy voice',
        useCases: ['character', 'youtube'],
        tags: ['rugged', 'warm', 'cowboy', 'male', 'American'],
    },
    {
        id: 'john-morgan',
        name: 'John Morgan',
        voiceName: 'ruirxsoakN0GWmGNIo04',
        elevenLabsId: 'ruirxsoakN0GWmGNIo04',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gritty, rugged cowboy voice',
        useCases: ['character', 'youtube'],
        tags: ['gritty', 'rugged', 'cowboy', 'male', 'American'],
    },
    {
        id: 'wyatt',
        name: 'Wyatt',
        voiceName: 'YXpFCvM1S3JbWEJhoskW',
        elevenLabsId: 'YXpFCvM1S3JbWEJhoskW',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Wise rustic cowboy voice',
        useCases: ['character', 'youtube'],
        tags: ['wise', 'rustic', 'cowboy', 'male', 'American'],
    },
    {
        id: 'david-cowboy',
        name: 'David (Cowboy)',
        voiceName: 'OYWwCdDHouzDwiZJWOOu',
        elevenLabsId: 'OYWwCdDHouzDwiZJWOOu',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gruff cowboy voice',
        useCases: ['character', 'youtube'],
        tags: ['gruff', 'cowboy', 'male', 'American'],
    },
    {
        id: 'carter',
        name: 'Carter',
        voiceName: 'qNkzaJoHLLdpvgh5tISm',
        elevenLabsId: 'qNkzaJoHLLdpvgh5tISm',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Rich, smooth and rugged male voice',
        useCases: ['character', 'youtube'],
        tags: ['rich', 'smooth', 'rugged', 'male', 'American'],
    },
    {
        id: 'jerry-b',
        name: 'Jerry B.',
        voiceName: '9PVP7ENhDskL0KYHAKtD',
        elevenLabsId: '9PVP7ENhDskL0KYHAKtD',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Southern/cowboy male voice',
        useCases: ['character', 'youtube'],
        tags: ['southern', 'cowboy', 'male', 'American'],
    },
    {
        id: 'spuds-oxley',
        name: 'Spuds Oxley',
        voiceName: 'NOpBlnGInO9m6vDvFkFC',
        elevenLabsId: 'NOpBlnGInO9m6vDvFkFC',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Middle Aged',
        description: 'Wise and approachable character voice',
        useCases: ['character', 'youtube'],
        tags: ['wise', 'approachable', 'character', 'male', 'American'],
    },
    {
        id: 'jarnathan',
        name: 'Jarnathan',
        voiceName: 'c6SfcYrb2t09NHXiT80T',
        elevenLabsId: 'c6SfcYrb2t09NHXiT80T',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Confident and versatile male voice',
        useCases: ['character', 'youtube'],
        tags: ['confident', 'versatile', 'character', 'male', 'American'],
    },
    {
        id: 'northern-terry',
        name: 'Northern Terry',
        voiceName: 'wo6udizrrtpIxWGp2qJk',
        elevenLabsId: 'wo6udizrrtpIxWGp2qJk',
        category: 'Character',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Northern English character voice',
        useCases: ['character', 'youtube'],
        tags: ['northern', 'British', 'character', 'male'],
    },
    {
        id: 'kuon',
        name: 'Kuon',
        voiceName: 'B8gJV1IhpuegLxdpXFOE',
        elevenLabsId: 'B8gJV1IhpuegLxdpXFOE',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Cheerful, clear and steady male voice',
        useCases: ['character', 'youtube'],
        tags: ['cheerful', 'clear', 'steady', 'male', 'American'],
    },
    {
        id: 'lutz',
        name: 'Lutz',
        voiceName: '9yzdeviXkFddZ4Oz8Mok',
        elevenLabsId: '9yzdeviXkFddZ4Oz8Mok',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Chuckling, giggly and cheerful male voice',
        useCases: ['character', 'youtube'],
        tags: ['chuckling', 'giggly', 'cheerful', 'male', 'American'],
    },
    {
        id: 'archer',
        name: 'Archer',
        voiceName: 'L0Dsvb3SLTyegXwtm47J',
        elevenLabsId: 'L0Dsvb3SLTyegXwtm47J',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Character voice for adventure and action',
        useCases: ['character', 'youtube'],
        tags: ['adventure', 'action', 'character', 'male', 'American'],
    },
    {
        id: 'xavier',
        name: 'Xavier',
        voiceName: 'YOq2y2Up4RgXP2HyXjE5',
        elevenLabsId: 'YOq2y2Up4RgXP2HyXjE5',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Dominating, metallic announcer voice',
        useCases: ['character', 'youtube'],
        tags: ['dominating', 'metallic', 'announcer', 'male', 'American'],
    },
    {
        id: 'jessica-bogart-villain',
        name: 'Jessica Anne Bogart (Villain)',
        voiceName: 'flHkNRp1BlvT73UL6gyz',
        elevenLabsId: 'flHkNRp1BlvT73UL6gyz',
        category: 'Character',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Eloquent villain female voice',
        useCases: ['character', 'youtube'],
        tags: ['eloquent', 'villain', 'character', 'female', 'American'],
    },
    {
        id: 'marshal',
        name: 'Marshal',
        voiceName: 'nzeAacJi50IvxcyDnMXa',
        elevenLabsId: 'nzeAacJi50IvxcyDnMXa',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Friendly, funny professor character voice',
        useCases: ['character', 'youtube'],
        tags: ['friendly', 'funny', 'professor', 'character', 'male', 'American'],
    },
    {
        id: 'taksh',
        name: 'Taksh',
        voiceName: 'qDuRKMlYmrm8trt5QyBn',
        elevenLabsId: 'qDuRKMlYmrm8trt5QyBn',
        category: 'Character',
        gender: 'male',
        accent: 'Indian',
        language: 'English',
        age: 'Adult',
        description: 'Calm, serious and smooth male voice',
        useCases: ['character', 'youtube'],
        tags: ['calm', 'serious', 'smooth', 'Indian', 'male'],
    },
    {
        id: 'nathan',
        name: 'Nathan',
        voiceName: 'x70vRnQBMBu4FAYhjJbO',
        elevenLabsId: 'x70vRnQBMBu4FAYhjJbO',
        category: 'Character',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Virtual radio host voice',
        useCases: ['character', 'youtube'],
        tags: ['virtual', 'radio', 'host', 'male', 'American'],
    },

    // =========================================
    // MEDITATION & ASMR VOICES (Calm, Soothing, Relaxing)
    // Great for: Meditation, ASMR, sleep, relaxation content
    // =========================================
    {
        id: 'natasha',
        name: 'Natasha',
        voiceName: 'Atp5cNFg1Wj5gyKD7HWV',
        elevenLabsId: 'Atp5cNFg1Wj5gyKD7HWV',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gentle meditation female voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['gentle', 'meditation', 'female', 'American'],
    },
    {
        id: 'emily-meditative',
        name: 'Emily (Meditative)',
        voiceName: '1cxc5c3E9K6F1wlqOJGV',
        elevenLabsId: '1cxc5c3E9K6F1wlqOJGV',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Gentle, soft and meditative female voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['gentle', 'soft', 'meditative', 'female', 'American'],
    },
    {
        id: 'viraj-smooth',
        name: 'Viraj (Smooth)',
        voiceName: '1U02n4nD6AdIZ9CjF053',
        elevenLabsId: '1U02n4nD6AdIZ9CjF053',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'Indian',
        language: 'English',
        age: 'Adult',
        description: 'Smooth and gentle male voice for meditation',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['smooth', 'gentle', 'Indian', 'male'],
    },
    {
        id: 'nate',
        name: 'Nate',
        voiceName: 'HgyIHe81F3nXywNwkraY',
        elevenLabsId: 'HgyIHe81F3nXywNwkraY',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Sultry, whispery and seductive male voice',
        useCases: ['sleep', 'asmr'],
        tags: ['sultry', 'whispery', 'seductive', 'male', 'American'],
    },
    {
        id: 'benjamin',
        name: 'Benjamin',
        voiceName: 'LruHrtVF6PSyGItzMNHS',
        elevenLabsId: 'LruHrtVF6PSyGItzMNHS',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, warm and calming male voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['deep', 'warm', 'calming', 'male', 'American'],
    },
    {
        id: 'clara',
        name: 'Clara',
        voiceName: 'Qggl4b0xRMiqOwhPtVWT',
        elevenLabsId: 'Qggl4b0xRMiqOwhPtVWT',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Relaxing, calm and soothing female voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['relaxing', 'calm', 'soothing', 'female', 'American'],
    },
    {
        id: 'aimee',
        name: 'AImee',
        voiceName: 'zA6D7RyKdc2EClouEMkP',
        elevenLabsId: 'zA6D7RyKdc2EClouEMkP',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Tranquil ASMR and meditation female voice',
        useCases: ['sleep', 'asmr'],
        tags: ['tranquil', 'ASMR', 'meditation', 'female', 'American'],
    },
    {
        id: 'allison',
        name: 'Allison',
        voiceName: '1wGbFxmAM3Fgw63G1zZJ',
        elevenLabsId: '1wGbFxmAM3Fgw63G1zZJ',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Calm, soothing and meditative female voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['calm', 'soothing', 'meditative', 'female', 'American'],
    },
    {
        id: 'theodore-hq',
        name: 'Theodore HQ',
        voiceName: 'hqfrgApggtO1785R4Fsn',
        elevenLabsId: 'hqfrgApggtO1785R4Fsn',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Serene and grounded male voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['serene', 'grounded', 'male', 'American'],
    },
    {
        id: 'koraly',
        name: 'Koraly',
        voiceName: 'sH0WdfE5fsKuM2otdQZr',
        elevenLabsId: 'sH0WdfE5fsKuM2otdQZr',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Soft-spoken and gentle female voice',
        useCases: ['sleep', 'asmr'],
        tags: ['soft-spoken', 'gentle', 'female', 'American'],
    },
    {
        id: 'leon',
        name: 'Leon',
        voiceName: 'MJ0RnG71ty4LH3dvNfSd',
        elevenLabsId: 'MJ0RnG71ty4LH3dvNfSd',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Soothing and grounded male voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['soothing', 'grounded', 'male', 'American'],
    },
    {
        id: 'priyanka',
        name: 'Priyanka',
        voiceName: 'BpjGufoPiobT79j2vtj4',
        elevenLabsId: 'BpjGufoPiobT79j2vtj4',
        category: 'Meditation & ASMR',
        gender: 'female',
        accent: 'Indian',
        language: 'English',
        age: 'Adult',
        description: 'Calm, neutral and relaxed female voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['calm', 'neutral', 'relaxed', 'Indian', 'female'],
    },
    {
        id: 'sven',
        name: 'Sven',
        voiceName: 'Tsns2HvNFKfGiNjllgqo',
        elevenLabsId: 'Tsns2HvNFKfGiNjllgqo',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'Swedish',
        language: 'English',
        age: 'Adult',
        description: 'Emotional and nice male voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['emotional', 'nice', 'Swedish', 'male'],
    },
    {
        id: 'nathaniel',
        name: 'Nathaniel',
        voiceName: 'AeRdCCKzvd23BpJoofzx',
        elevenLabsId: 'AeRdCCKzvd23BpJoofzx',
        category: 'Meditation & ASMR',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Engaging, British and calm male voice',
        useCases: ['sleep', 'asmr', 'youtube'],
        tags: ['engaging', 'British', 'calm', 'male'],
    },

    // =========================================
    // ANNOUNCER & RADIO VOICES (Broadcasting, DJs, Trailers)
    // Great for: Movie trailers, sports, radio, broadcasting
    // =========================================
    {
        id: 'phil',
        name: 'Phil',
        voiceName: 'LG95yZDEHg6fCZdQjLqj',
        elevenLabsId: 'LG95yZDEHg6fCZdQjLqj',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Explosive, passionate announcer voice',
        useCases: ['youtube', 'studio'],
        tags: ['explosive', 'passionate', 'announcer', 'male', 'American'],
    },
    {
        id: 'johnny-dynamite',
        name: 'Johnny Dynamite',
        voiceName: 'CeNX9CMwmxDxUF5Q2Inm',
        elevenLabsId: 'CeNX9CMwmxDxUF5Q2Inm',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Vintage radio DJ voice',
        useCases: ['youtube', 'studio'],
        tags: ['vintage', 'radio', 'DJ', 'male', 'American'],
    },
    {
        id: 'blondie-radio',
        name: 'Blondie (Radio Host)',
        voiceName: 'st7NwhTPEzqo2riw7qWC',
        elevenLabsId: 'st7NwhTPEzqo2riw7qWC',
        category: 'Announcer & Radio',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Female radio host voice',
        useCases: ['youtube', 'studio'],
        tags: ['radio', 'host', 'female', 'American'],
    },
    {
        id: 'rachel-m',
        name: 'Rachel M',
        voiceName: 'aD6riP1btT197c6dACmy',
        elevenLabsId: 'aD6riP1btT197c6dACmy',
        category: 'Announcer & Radio',
        gender: 'female',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'Pro British radio presenter voice',
        useCases: ['youtube', 'studio'],
        tags: ['British', 'radio', 'presenter', 'professional', 'female'],
    },
    {
        id: 'david-movie-trailer',
        name: 'David (Movie Trailer)',
        voiceName: 'FF7KdobWPaiR0vkcALHF',
        elevenLabsId: 'FF7KdobWPaiR0vkcALHF',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Movie trailer narrator voice',
        useCases: ['youtube', 'studio'],
        tags: ['movie trailer', 'narrator', 'epic', 'male', 'American'],
    },
    {
        id: 'rex-thunder',
        name: 'Rex Thunder',
        voiceName: 'mtrellq69YZsNwzUSyXh',
        elevenLabsId: 'mtrellq69YZsNwzUSyXh',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep and tough male announcer voice',
        useCases: ['youtube', 'studio'],
        tags: ['deep', 'tough', 'announcer', 'male', 'American'],
    },
    {
        id: 'ed',
        name: 'Ed',
        voiceName: 'dHd5gvgSOzSfduK4CvEg',
        elevenLabsId: 'dHd5gvgSOzSfduK4CvEg',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Late night announcer voice',
        useCases: ['youtube', 'studio'],
        tags: ['late night', 'announcer', 'male', 'American'],
    },
    {
        id: 'british-football-announcer',
        name: 'British Football Announcer',
        voiceName: 'gU0LNdkMOQCOrPrwtbee',
        elevenLabsId: 'gU0LNdkMOQCOrPrwtbee',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'British',
        language: 'English',
        age: 'Adult',
        description: 'British football announcer voice',
        useCases: ['youtube', 'studio'],
        tags: ['British', 'football', 'announcer', 'sports', 'male'],
    },
    {
        id: 'austin',
        name: 'Austin',
        voiceName: 'Bj9UqZbhQsanLzgalpEG',
        elevenLabsId: 'Bj9UqZbhQsanLzgalpEG',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep, raspy and authentic male voice',
        useCases: ['youtube', 'studio'],
        tags: ['deep', 'raspy', 'authentic', 'male', 'American'],
    },
    {
        id: 'smith',
        name: 'Smith',
        voiceName: 'TmNe0cCqkZBMwPWOd3RD',
        elevenLabsId: 'TmNe0cCqkZBMwPWOd3RD',
        category: 'Announcer & Radio',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Mellow, spontaneous and bassy male voice',
        useCases: ['youtube', 'studio'],
        tags: ['mellow', 'spontaneous', 'bassy', 'male', 'American'],
    },

    // =========================================
    // CONVERSATIONAL VOICES (Natural, Chatbots, Support, Casual)
    // Great for: Chatbots, customer support, casual everyday, tutorials
    // =========================================
    {
        id: 'blondie-conversational',
        name: 'Blondie',
        voiceName: 'exsUS4vynmxd379XN4yO',
        elevenLabsId: 'exsUS4vynmxd379XN4yO',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Conversational female voice',
        useCases: ['studio', 'youtube'],
        tags: ['conversational', 'female', 'American'],
    },
    {
        id: 'adeline',
        name: 'Adeline',
        voiceName: '5l5f8iK3YPeGga21rQIX',
        elevenLabsId: '5l5f8iK3YPeGga21rQIX',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Feminine and conversational female voice',
        useCases: ['studio', 'youtube'],
        tags: ['feminine', 'conversational', 'female', 'American'],
    },
    {
        id: 'sam-support',
        name: 'Sam (Support)',
        voiceName: 'scOwDtmlUjD3prqpp97I',
        elevenLabsId: 'scOwDtmlUjD3prqpp97I',
        category: 'Conversational',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Support agent male voice',
        useCases: ['studio', 'youtube'],
        tags: ['support', 'agent', 'male', 'American'],
    },
    {
        id: 'angela',
        name: 'Angela',
        voiceName: 'FUfBrNit0NNZAwb58KWH',
        elevenLabsId: 'FUfBrNit0NNZAwb58KWH',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Conversational and friendly female voice',
        useCases: ['studio', 'youtube'],
        tags: ['conversational', 'friendly', 'female', 'American'],
    },
    {
        id: 'mark-natural',
        name: 'Mark (Natural)',
        voiceName: 'UgBBYS2sOqTuMpoF3BR0',
        elevenLabsId: 'UgBBYS2sOqTuMpoF3BR0',
        category: 'Conversational',
        gender: 'male',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Natural conversations male voice',
        useCases: ['studio', 'youtube'],
        tags: ['natural', 'conversations', 'male', 'American'],
    },
    {
        id: 'jessica-bogart-chatty',
        name: 'Jessica Anne Bogart (Chatty)',
        voiceName: 'g6xIsTj2HwM6VR4iXFCw',
        elevenLabsId: 'g6xIsTj2HwM6VR4iXFCw',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Chatty and friendly female voice',
        useCases: ['studio', 'youtube'],
        tags: ['chatty', 'friendly', 'female', 'American'],
    },
    {
        id: 'hope-upbeat',
        name: 'Hope (Upbeat)',
        voiceName: 'tnSpp4vdxKPjI9w0GnoV',
        elevenLabsId: 'tnSpp4vdxKPjI9w0GnoV',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Upbeat and clear female voice',
        useCases: ['studio', 'youtube', 'shorts'],
        tags: ['upbeat', 'clear', 'female', 'American'],
    },
    {
        id: 'hope-bubbly',
        name: 'Hope (Bubbly)',
        voiceName: 'uYXf8XasLslADfZ2MB4u',
        elevenLabsId: 'uYXf8XasLslADfZ2MB4u',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Young Adult',
        description: 'Bubbly, gossipy and girly female voice',
        useCases: ['studio', 'shorts', 'youtube'],
        tags: ['bubbly', 'gossipy', 'girly', 'female', 'American'],
    },
    {
        id: 'monika-sogam',
        name: 'Monika Sogam',
        voiceName: '2zRM7PkgwBPiau2jvVXc',
        elevenLabsId: '2zRM7PkgwBPiau2jvVXc',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Deep and natural female voice',
        useCases: ['studio', 'youtube'],
        tags: ['deep', 'natural', 'female', 'American'],
    },
    {
        id: 'guadeloupe',
        name: 'Guadeloupe Merryweather',
        voiceName: 'kUUTqKQ05NMGulF08DDf',
        elevenLabsId: 'kUUTqKQ05NMGulF08DDf',
        category: 'Conversational',
        gender: 'female',
        accent: 'American',
        language: 'English',
        age: 'Adult',
        description: 'Emotional female voice',
        useCases: ['studio', 'youtube'],
        tags: ['emotional', 'female', 'American'],
    },
]

// Helper functions
export function getVoiceById(id: string): VoiceData | undefined {
    return VOICES_DATA.find(v => v.id === id)
}

export function getVoiceByName(name: string): VoiceData | undefined {
    return VOICES_DATA.find(v => v.voiceName.toLowerCase() === name.toLowerCase())
}

export function getVoicesByCategory(category: VoiceCategory): VoiceData[] {
    return VOICES_DATA.filter(v => v.category === category)
}

export function getVoicesByLanguage(language: string): VoiceData[] {
    return VOICES_DATA.filter(v => v.language.toLowerCase() === language.toLowerCase())
}

export function getVoicesByUseCase(useCase: string): VoiceData[] {
    return VOICES_DATA.filter(v => v.useCases.includes(useCase))
}

export function searchVoices(query: string): VoiceData[] {
    const q = query.toLowerCase()
    return VOICES_DATA.filter(v =>
        v.name.toLowerCase().includes(q) ||
        v.category.toLowerCase().includes(q) ||
        v.accent.toLowerCase().includes(q) ||
        v.description.toLowerCase().includes(q) ||
        v.tags.some(t => t.toLowerCase().includes(q))
    )
}

// Verified working preview URLs from ElevenLabs public CDN
// Fetched from https://api.elevenlabs.io/v1/voices (public, no auth needed)
const ELEVENLABS_PREVIEW_URLS: Record<string, string> = {
    'CwhRBWXzGAHq8TQ4Fs17': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/CwhRBWXzGAHq8TQ4Fs17/58ee3ff5-f6f2-4628-93b8-e38eb31806b0.mp3', // Roger
    'EXAVITQu4vr4xnSDxMaL': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/01a3e33c-6e99-4ee7-8543-ff2216a32186.mp3', // Sarah
    'FGY2WhTYpPnrIDTdsKH5': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67341759-ad08-41a5-be6e-de12fe448618.mp3', // Laura
    'IKne3meq5aSn9XLyUdCD': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/IKne3meq5aSn9XLyUdCD/102de6f2-22ed-43e0-a1f1-111fa75c5481.mp3', // Charlie
    'JBFqnCBsd6RMkjVDRZzb': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/JBFqnCBsd6RMkjVDRZzb/e6206d1a-0721-4787-aafb-06a6e705cac5.mp3', // George
    'N2lVS1w4EtoT3dr4eOWO': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/N2lVS1w4EtoT3dr4eOWO/ac833bd8-ffda-4938-9ebc-b0f99ca25481.mp3', // Callum
    'SAz9YHcvj6GT2YYXdXww': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/SAz9YHcvj6GT2YYXdXww/e6c95f0b-2227-491a-b3d7-2249240decb7.mp3', // River
    'TX3LPaxmHKxFdv7VOQHJ': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/TX3LPaxmHKxFdv7VOQHJ/63148076-6363-42db-aea8-31424308b92c.mp3', // Liam
    'Xb7hH8MSUJpSbSDYk0k2': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/Xb7hH8MSUJpSbSDYk0k2/d10f7534-11f6-41fe-a012-2de1e482d336.mp3', // Alice
    'XrExE9yKIg1WjnnlVkGX': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/XrExE9yKIg1WjnnlVkGX/b930e18d-6b4d-466e-bab2-0ae97c6d8535.mp3', // Matilda
    'bIHbv24MWmeRgasZH58o': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/bIHbv24MWmeRgasZH58o/8caf8f3d-ad29-4980-af41-53f20c72d7a4.mp3', // Will
    'cgSgspJ2msm6clMCkdW9': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11683d45a.mp3', // Jessica
    'cjVigY5qzO86Huf0OWal': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/cjVigY5qzO86Huf0OWal/d098fda0-6456-4030-b3d8-63aa048c9070.mp3', // Eric
    'iP95p4xoKVk53GoZ742B': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/iP95p4xoKVk53GoZ742B/3f4bde72-cc48-40dd-829f-57fbf906f4d7.mp3', // Chris
    'nPczCjzI2devNBz1zQrb': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/nPczCjzI2devNBz1zQrb/2dd3e72c-4fd3-42f1-93ea-abc5d4e5aa1d.mp3', // Brian
    'onwK4e9ZLuTAKqWW03F9': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/onwK4e9ZLuTAKqWW03F9/7eee0236-1a72-4b86-b303-5dcadc007ba9.mp3', // Daniel
    'pFZP5JQG7iQjIQuC4Bku': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3', // Lily
    'pqHfZKP75CvOlQylNhV4': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pqHfZKP75CvOlQylNhV4/d782b3ff-84ba-4029-848c-acf01285524d.mp3', // Bill
    '21m00Tcm4TlvDq8ikWAM': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/d49e4fba-c42b-46e0-ad4d-0ca1bea8a7a4.mp3', // Rachel
    '9BWtsMINqrJLrRacOk9x': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/9BWtsMINqrJLrRacOk9x/405766b2-1e3c-436e-8526-53c20ad3a593.mp3', // Aria
    'XB0fDUnXU5powFXDhCwa': 'https://storage.googleapis.com/eleven-public-prod/premade/voices/XB0fDUnXU5powFXDhCwa/942356dc-57f2-4e04-98e5-d21614354c11.mp3', // Charlotte
}

// Get the preview URL for a voice
// Priority: 1) Verified ElevenLabs CDN  2) Kie.ai static CDN fallback
export function getVoicePreviewUrl(voice: VoiceData): string | null {
    if (voice.elevenLabsId) {
        // Use verified ElevenLabs URL if available (always works)
        if (ELEVENLABS_PREVIEW_URLS[voice.elevenLabsId]) {
            return ELEVENLABS_PREVIEW_URLS[voice.elevenLabsId]
        }
        // Fallback to Kie.ai CDN (works for some voices)
        return `${VOICE_PREVIEW_BASE_URL}/${voice.elevenLabsId}.mp3`
    }
    return null
}

// Get all unique values for filters
export function getAllLanguages(): string[] {
    return [...new Set(VOICES_DATA.map(v => v.language))].sort()
}

export function getAllAccents(): string[] {
    return [...new Set(VOICES_DATA.map(v => v.accent))].sort()
}

export function getAllUseCases(): string[] {
    const useCases = new Set<string>()
    VOICES_DATA.forEach(v => v.useCases.forEach(uc => useCases.add(uc)))
    return [...useCases].sort()
}

// Generate a deterministic usage count based on voice name (for display purposes)
export function generateUsageCount(voiceName: string): number {
    let hash = 0
    for (let i = 0; i < voiceName.length; i++) {
        const char = voiceName.charCodeAt(i)
        hash = ((hash << 5) - hash) + char
        hash = hash & hash
    }
    return Math.abs(hash % 900000) + 100000
}
