-- =============================================================================
-- STEP 25 PRE-CHECK — who in this CSV already has a grant, and where from?
-- =============================================================================
-- READ ONLY. Changes nothing. Run before step25 to see exactly what will and
-- will not be inserted, including anything the Pabbly webhook already granted.
-- =============================================================================
WITH csv_emails(email) AS (
  VALUES
    ('adbabhijeet@gmail.com'),
    ('aditimyworld98@gmail.com'),
    ('afzal.bagwan333@gmail.com'),
    ('akhilesh11021998@gmail.com'),
    ('akiragoyal022@gmail.com'),
    ('akshayramtekkar54@gmail.com'),
    ('amanvishwakarmabab@gmail.com'),
    ('amarskumbhar007@gmail.com'),
    ('amaru79now@gmail.com'),
    ('ambujbhardwaj2001@gmail.com'),
    ('amitbharwan1992@gmail.com'),
    ('amitdabas83@gmail.com'),
    ('amiya505645w@gmail.com'),
    ('aparnasingh1797@gmail.com'),
    ('apurvaramteke29@yahoo.in'),
    ('baishakhichakraborty851@gmail.com'),
    ('banosekar.kamlesh@gmail.com'),
    ('bennmoses.2006@gmail.com'),
    ('boniface.grabbus@gmail.com'),
    ('chadha.hiten@gmail.com'),
    ('chaitanyababar1700@gmail.com'),
    ('charanrajk011@gmail.com'),
    ('chatvandana.mishra@gmail.com'),
    ('chirasmita786@gmail.com'),
    ('deachen54@gmail.com'),
    ('deepa.r.gaikwad@gmail.com'),
    ('dey.saurav@gmail.com'),
    ('deyanumita098@gmail.com'),
    ('dhanushakki111@gmail.com'),
    ('digitalmarketingcorp3@gmail.com'),
    ('dr.jyotiangural@gmail.com'),
    ('eileennanish@gmail.com'),
    ('gargritika.93@gmail.com'),
    ('gauravsaxena.dev@gmail.com'),
    ('gouthamkrishnareddypaisa@gmail.com'),
    ('gurps793@gmail.com'),
    ('harshitadesigns02@gmail.com'),
    ('harshithas087@gmail.com'),
    ('hussainifathema11@gmail.com'),
    ('iamolwrites@gmail.com'),
    ('instagram.business0811@gmail.com'),
    ('ishitwatiwari08@gmail.com'),
    ('kamnachadha@gmail.com'),
    ('kartikey.4424@gmail.com'),
    ('keshavgoyal0210@gmail.com'),
    ('khanfateen68@gmail.com'),
    ('kharbnarveer@gmail.com'),
    ('kritisharmaa@gmail.com'),
    ('krjayakeerti@gmail.com'),
    ('laxmipriya2117@gmail.com'),
    ('lniteesha@gmail.com'),
    ('mahendra.onlineshop@rediffmail.com'),
    ('manisha0806sharma@gmail.com'),
    ('manojrajput3631@gmail.com'),
    ('mnprtkrunique@gmail.com'),
    ('nallinkundalia5@gmail.com'),
    ('neetadanwar@gmail.com'),
    ('nehatiwaribt@gmail.com'),
    ('nunesindhu123@gmail.com'),
    ('owais1807@outlook.com'),
    ('padvigaurangm@gmail.com'),
    ('phataknandita.007@gmail.com'),
    ('pklove2709@gmail.com'),
    ('pmsss31101@gmail.com'),
    ('pramodkumar.kanaka@gmail.com'),
    ('prasadkulkarnib@gmail.com'),
    ('preetiochhane025@gmail.com'),
    ('priya20sethi@gmail.com'),
    ('priyasumit2405@gmail.com'),
    ('puneetkmr189@gmail.com'),
    ('rahuldas12121989@gmail.com'),
    ('raina.vivek121@gmail.com'),
    ('rakeshsinha2296@gmail.com'),
    ('ramdas.diwaka@gmail.com'),
    ('rameshmaganti55@gmail.com'),
    ('rbe818181@gmail.com'),
    ('rguliani1@gmail.com'),
    ('rh8499004@gmail.com'),
    ('riteshde560@gmail.com'),
    ('ritu.motial@gmail.com'),
    ('rohitvilla27@gmail.com'),
    ('roshanjaiswal0011@gmail.com'),
    ('sahil013saini03@gmail.com'),
    ('sairamtt03@gmail.com'),
    ('sakshibondre09@gmail.com'),
    ('samrastic0212@gmail.com'),
    ('sandeepdas46@gmail.com'),
    ('sanjay.thogiti@gmail.com'),
    ('sarthakrajdeo@gmail.com'),
    ('saurabhchelsea17@gmail.com'),
    ('sayed.mohsin@outlook.com'),
    ('shahbazansari2367@gmail.com'),
    ('shaikhayesha2203@gmail.com'),
    ('shankarwarshiv@gmail.com'),
    ('sharadtyagi2005@gmail.com'),
    ('sheetalpawarp@gmail.com'),
    ('shoutout2santosh@gmail.com'),
    ('shriya.kriti@gmail.com'),
    ('shweta6791@gmail.com'),
    ('siddharth7n@gmail.com'),
    ('subanto_dhar@yahoo.co.in'),
    ('suneeldeshpande83@gmail.com'),
    ('surabhidk@gmail.com'),
    ('sushanthvs96@gmail.com'),
    ('swapnilgund17@gmail.com'),
    ('telisanket2002@gmail.com'),
    ('thanushvarath2000@gmail.com'),
    ('univajpuneet30@gmail.com'),
    ('vaishaliherode@gmail.com'),
    ('vermaprachii018@gmail.com'),
    ('vishal0072rathod@gmail.com'),
    ('vivekkuntal0369@gmail.com'),
    ('www.sukithcoorg@gmail.com'),
    ('zameer1611@gmail.com')
)
SELECT
    COALESCE(g.source, '-- NOT GRANTED YET --') AS came_from,
    COALESCE(g.batch_key, '')                   AS batch,
    COUNT(*)                                    AS people,
    COUNT(*) FILTER (WHERE g.claimed)           AS already_claimed
FROM csv_emails c
LEFT JOIN public.pending_credit_grants g ON g.email = LOWER(BTRIM(c.email))
GROUP BY 1, 2
ORDER BY 1, 2;

-- The individual names, if you want to eyeball them:
WITH csv_emails(email) AS (
  VALUES
    ('adbabhijeet@gmail.com'),
    ('aditimyworld98@gmail.com'),
    ('afzal.bagwan333@gmail.com'),
    ('akhilesh11021998@gmail.com'),
    ('akiragoyal022@gmail.com'),
    ('akshayramtekkar54@gmail.com'),
    ('amanvishwakarmabab@gmail.com'),
    ('amarskumbhar007@gmail.com'),
    ('amaru79now@gmail.com'),
    ('ambujbhardwaj2001@gmail.com'),
    ('amitbharwan1992@gmail.com'),
    ('amitdabas83@gmail.com'),
    ('amiya505645w@gmail.com'),
    ('aparnasingh1797@gmail.com'),
    ('apurvaramteke29@yahoo.in'),
    ('baishakhichakraborty851@gmail.com'),
    ('banosekar.kamlesh@gmail.com'),
    ('bennmoses.2006@gmail.com'),
    ('boniface.grabbus@gmail.com'),
    ('chadha.hiten@gmail.com'),
    ('chaitanyababar1700@gmail.com'),
    ('charanrajk011@gmail.com'),
    ('chatvandana.mishra@gmail.com'),
    ('chirasmita786@gmail.com'),
    ('deachen54@gmail.com'),
    ('deepa.r.gaikwad@gmail.com'),
    ('dey.saurav@gmail.com'),
    ('deyanumita098@gmail.com'),
    ('dhanushakki111@gmail.com'),
    ('digitalmarketingcorp3@gmail.com'),
    ('dr.jyotiangural@gmail.com'),
    ('eileennanish@gmail.com'),
    ('gargritika.93@gmail.com'),
    ('gauravsaxena.dev@gmail.com'),
    ('gouthamkrishnareddypaisa@gmail.com'),
    ('gurps793@gmail.com'),
    ('harshitadesigns02@gmail.com'),
    ('harshithas087@gmail.com'),
    ('hussainifathema11@gmail.com'),
    ('iamolwrites@gmail.com'),
    ('instagram.business0811@gmail.com'),
    ('ishitwatiwari08@gmail.com'),
    ('kamnachadha@gmail.com'),
    ('kartikey.4424@gmail.com'),
    ('keshavgoyal0210@gmail.com'),
    ('khanfateen68@gmail.com'),
    ('kharbnarveer@gmail.com'),
    ('kritisharmaa@gmail.com'),
    ('krjayakeerti@gmail.com'),
    ('laxmipriya2117@gmail.com'),
    ('lniteesha@gmail.com'),
    ('mahendra.onlineshop@rediffmail.com'),
    ('manisha0806sharma@gmail.com'),
    ('manojrajput3631@gmail.com'),
    ('mnprtkrunique@gmail.com'),
    ('nallinkundalia5@gmail.com'),
    ('neetadanwar@gmail.com'),
    ('nehatiwaribt@gmail.com'),
    ('nunesindhu123@gmail.com'),
    ('owais1807@outlook.com'),
    ('padvigaurangm@gmail.com'),
    ('phataknandita.007@gmail.com'),
    ('pklove2709@gmail.com'),
    ('pmsss31101@gmail.com'),
    ('pramodkumar.kanaka@gmail.com'),
    ('prasadkulkarnib@gmail.com'),
    ('preetiochhane025@gmail.com'),
    ('priya20sethi@gmail.com'),
    ('priyasumit2405@gmail.com'),
    ('puneetkmr189@gmail.com'),
    ('rahuldas12121989@gmail.com'),
    ('raina.vivek121@gmail.com'),
    ('rakeshsinha2296@gmail.com'),
    ('ramdas.diwaka@gmail.com'),
    ('rameshmaganti55@gmail.com'),
    ('rbe818181@gmail.com'),
    ('rguliani1@gmail.com'),
    ('rh8499004@gmail.com'),
    ('riteshde560@gmail.com'),
    ('ritu.motial@gmail.com'),
    ('rohitvilla27@gmail.com'),
    ('roshanjaiswal0011@gmail.com'),
    ('sahil013saini03@gmail.com'),
    ('sairamtt03@gmail.com'),
    ('sakshibondre09@gmail.com'),
    ('samrastic0212@gmail.com'),
    ('sandeepdas46@gmail.com'),
    ('sanjay.thogiti@gmail.com'),
    ('sarthakrajdeo@gmail.com'),
    ('saurabhchelsea17@gmail.com'),
    ('sayed.mohsin@outlook.com'),
    ('shahbazansari2367@gmail.com'),
    ('shaikhayesha2203@gmail.com'),
    ('shankarwarshiv@gmail.com'),
    ('sharadtyagi2005@gmail.com'),
    ('sheetalpawarp@gmail.com'),
    ('shoutout2santosh@gmail.com'),
    ('shriya.kriti@gmail.com'),
    ('shweta6791@gmail.com'),
    ('siddharth7n@gmail.com'),
    ('subanto_dhar@yahoo.co.in'),
    ('suneeldeshpande83@gmail.com'),
    ('surabhidk@gmail.com'),
    ('sushanthvs96@gmail.com'),
    ('swapnilgund17@gmail.com'),
    ('telisanket2002@gmail.com'),
    ('thanushvarath2000@gmail.com'),
    ('univajpuneet30@gmail.com'),
    ('vaishaliherode@gmail.com'),
    ('vermaprachii018@gmail.com'),
    ('vishal0072rathod@gmail.com'),
    ('vivekkuntal0369@gmail.com'),
    ('www.sukithcoorg@gmail.com'),
    ('zameer1611@gmail.com')
)
SELECT c.email,
       COALESCE(g.source, 'not granted yet') AS came_from,
       g.batch_key, g.grant_tier, g.claimed, g.source_order_id
FROM csv_emails c
LEFT JOIN public.pending_credit_grants g ON g.email = LOWER(BTRIM(c.email))
WHERE g.id IS NOT NULL
ORDER BY g.source, c.email;
